baseURL = "www.example.com"
languageCode = "en-us"
title = "Hugo Serif Theme"
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Qui est votre conseiller ?"
url = "/about/"
weight = 3
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4
[[menu.main]]
name = "Team"
url = "/team/"
weight = 2
[[menu.main]]
name = "Services"
url = "/services/"
weight = 1
[params]
google_analytics_id = ""
google_tag_manager_id = ""
[params.footer]
copyright_text = "Free Hugo theme by <a class=\"zerostatic\" href=\"https://www.zerostatic.io\">www.zerostatic.io</a>"
[params.homepage]
hide_view_all_services = false
show_call_box = true
[params.homepage_meta_tags]
meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
meta_og_title = "Hugo Serif Theme"
meta_og_type = "website"
meta_og_url = "https://hugo-serif.netlify.app"
meta_twitter_card = "summary"
meta_twitter_creator = "@zerostaticio"
meta_twitter_site = "@zerostaticio"
[params.logo]
alt = "Serif - A Hugo Business Theme"
desktop = "images/logo/logo.svg"
desktop_height = "36px"
mobile = "images/logo/logo-mobile.svg"
mobile_height = "36px"
[params.team]
summary_large_truncate = 120
